data_ingestion :
  raw_data_path : "data/raw/raw.npz"
  ingested_train_path : "data/ingested/train"
  ingested_test_path : "data/ingested/test"
data_preprocessing :
  processed_data_path : "data/processed/fashion_mnist_scaled.npz"

preprocessing :
  val_size : 0.1
  random_state : 42

model_dir : "models"

train :
  epochs : 10
  batch_size : 32
  dropout_rate : 0.3
  dense_units : 128